name: Deploy delta
description: sf project deploy from delta package
inputs:
  sf_alias:
    required: true

runs:
  using: composite
  steps:
    - run: ./.github/workflows/reusable/scripts/deploy_delta.ps1 "$env:SF_ALIAS"
      shell: pwsh
      env:
        SF_ALIAS: ${{ inputs.sf_alias }}
