# sfdx-git-delta (`sf sgd`) — computes metadata differences between Git refs for package.xml generation.
name: SF install Git Delta plugin
description: Install sfdx-git-delta plugin

runs:
  using: composite
  steps:
    - run: ./.github/workflows/templates/scripts/install_sfdx_git_delta_plugin.ps1
      shell: pwsh
